name: Публикация в PyPI

on:
  workflow_run:
    workflows: ["Создание релиза"]
    types: [completed]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Получение исходного кода
      uses: actions/checkout@v4

    - name: Установка uv
      uses: astral-sh/setup-uv@v7

    - name: Установка Python
      run: uv python install

    - name: Сборка пакета
      run: uv build

    - name: Публикация в PyPI
      run: uv publish
      env:
        UV_PUBLISH_TOKEN: ${{ secrets.PYPI_TOKEN }}